### ISSUE TITLE
Bastion key handling needs to be improved

### ISSUE THREAD

**Issue by ibaldin** [fabric-testbed/fabrictestbed-extensions#151]
I had a wrong bastion key and fablib just kept on trying the postboot scripts that are executed as part of slice submit. It should've flagged the problem right away. It waited 4500 seconds until I without interrupting it fixed the key then it proceeded.

**Comment by sajith** [comment]
I also ran across this recently.  My bastion key expired, so I created a new one, but my configuration still was pointing to the old key.  So `Slice.submit()` kept trying with the old key, until there was enough authentication failures that triggered fail2ban.  

I think the problem is that `Slice.wait_ssh()` (invoked by `Slice.submit()`) keeps trying to connect to the nodes for a full 30 minutes, in 20 seconds intervals, regardless of the type of failure:

https://github.com/fabric-testbed/fabrictestbed-extensions/blob/7c3eff01540f95c4b0183623b70f85c6d4e420e1/fabrictestbed_extensions/fablib/slice.py#L1937-L1940

This is likely to lead to a lot of avoidable support tickets in the future. 

Perhaps we could try probing bastion with the supplied bastion related parameters,  and fail early if there's an authentication failure before invoking `wait_ssh()`?

To sketch out an idea:

```python
try:
    bastion_client = paramiko.SSHClient()
    bastion_client.set_missing_host_key_policy(paramiko.AutoAddPolicy)
    bastion_client.connect(
        hostname=os.getenv("FABRIC_BASTION_HOST"), 
        username=os.getenv("FABRIC_BASTION_USERNAME"), 
        key_filename=os.getenv("FABRIC_BASTION_KEY_LOCATION"), 
        passphrase=os.getenv("FABRIC_BASTION_KEY_PASSPHRASE"), 
        look_for_keys=False
    )
except paramiko.AuthenticationException as e:
    # Report error and give up
    logger.error(f"Auth error: {e}")
    raise e
except paramiko.SSHException as e:
    # Unsure how to handle this -- same as above maybe?
    logger.error(f"SSH error: {e}")
    raise e
except Exception as e:
    # Could this be a transient error? Should we keep re-trying in that case?
    logger.error(f"Some other error: {e}")
finally:
    bastion_client.close()
```

**Comment by ibaldin** [comment]
Definitely probing and failing early is the way to go.
