### ISSUE TITLE
sudo hostname resolution fails after running nat64.sh

### ISSUE THREAD

**Issue by cunha** [fabric-testbed/fabrictestbed-extensions#216]
Running the `nat64.sh` script causes `sudo` to complain it cannot resolve the hostname (e.g., when calling `node.execute()`). It seems like removing `127.0.0.53` from the resolvers list causes this.

**Comment by sajith** [comment]
@cunha Which notebook have you been using? Could this be an issue with [this notebook](https://github.com/fabric-testbed/jupyter-examples/blob/a1c1a32ed6abfd09452741d2b592c2d8c295a38f/fabric_examples/fablib_api/accessing_ipv4_services_from_ipv6_nodes/accessing_ipv4_services_from_ipv6_nodes.ipynb) (note that it is in a separate repository), rather than the library?

**Comment by cunha** [comment]
Correct. Closing and moving to https://github.com/fabric-testbed/jupyter-examples/issues/240.

**Comment by sajith** [comment]
Thank you. I could have clicked the button to transfer it there though. :-)
