### ISSUE TITLE
postboot on slice update/modify not working properly

### ISSUE THREAD

**Issue by hussamnasir** [fabric-testbed/fabrictestbed-extensions#261]
Here's the setup i tried that failed.
1. Create a 2 node WAN topology with L2 links between the nodes(one at each site). Interfaces set to "auto"
2. Submit slice
3. Created nodes with IP addresses assigned by fablib.
4. Modify the slice by adding third node at a third SITE
5. Add an interface tied to a new L3 network at each site. This interface is set to auto. Node routing for L3 networks is also set at this point with templates.
6. Submit(modify)
7. Upon slice being ready, 
Expectation: All nodes ready and interfaces have IP
What I got:  The extra added node (4) has its IP configure on the dataplane interface and route added. The other nodes that existed before the modify do not have their newly added Interface configure. Those interfaces are still down with no IP assignment.

Forcing a node.config() on those nodes forces the postboot config that was messed up.

**Comment by hussamnasir** [comment]
Here's the run thru.
1. Create your experiment using "create_l2network_wide_area_auto.ipynb" notebook.
2. Next run this block from 
3. https://github.com/fabric-testbed/mflib/blob/d71fc68dae6e724cdcfc39853d097c7f0bb1636e/mflib/mflib.py#L105
4. then submit

**Comment by sajith** [comment]
@hussamnasir Just a small update: I just got around to look into this, and I'm able to reproduce what you've described above, I think.  Thank you for the detailed steps.

I'm trying to work out what is going on for now.

**Comment by sajith** [comment]
Sorry, I spoke too early when I said I could reproduce this: what I "reproduced" seems to be a transient error from the testbed, not the error @hussamnasir describes above.

(On Tuesday Nov 7, the error I saw was that nodes did **not** get a management address.  However that is not the original issue.  On hindsight, I wish I had taken copies of logs or screenshot of the notebook, but it did not occur to me to do this at the time.)

Now, back to the actual issue.  This is way I have understood this: you create a slice following steps 1-5, then do `slice.submit()` (step 6), then do `MFLib.addMeasNode(slice)`, then do `slice.submit()` again. This will result in a modify operation.

![image](https://github.com/fabric-testbed/fabrictestbed-extensions/assets/23618/4afb18fc-f9b5-4960-a15c-d247e33e05d7)

The problem is that the interfaces added by MFLib (`Node1-meas_nic_Node1_MICH-p1`, `Node2-meas_nic_Node2_NCSA-p1`, and `meas-node-meas_nic_meas-node_EDC-p1`) do not have an IP address.  I am unsure if this is a fablib issue though.

There's a variation of the above: created a slice with steps 1-5, then do `MFLib.addMeasNode(slice)`, then do `slice.submit()`.  This should not involve a modify operation.  Result: two of the interfaces added by MFLib get an address, there's a third one that do not have an address.

![image](https://github.com/fabric-testbed/fabrictestbed-extensions/assets/23618/c827a774-bce9-4287-a8db-99692374c4d1)

I think postboot has nothing to do with this (or maybe I've misunderstood things), because for each of the nodes in the slice, `post_boot_commands` is an empty list:

```
{'Node1': {'fablib_data': {'instantiated': 'True',
   'run_update_commands': 'False',
   'post_boot_commands': [],
   'post_update_commands': []}},
 'Node2': {'fablib_data': {'instantiated': 'True',
   'run_update_commands': 'False',
   'post_boot_commands': [],
   'post_update_commands': []}},
 'meas-node': {'fablib_data': {'instantiated': 'True',
   'run_update_commands': 'False',
   'post_boot_commands': [],
   'post_update_commands': []}},
...
```

**Comment by hussamnasir** [comment]
Ah. At last. This is what I was looking for. It is in my opinion 99.9% the issue.

**Comment by sajith** [comment]
@hussamnasir I'm so sorry that this took such a long time, and thank you so much for your patience! The amount of state we're keeping around and the fact that a thread pool was invoking `Node.config()` and messed with my head.

My branch is really messy right now. I will clean things up and submit a PR for review later. Please bear with me for a few more days, because I have to be away.
